version: '3'

services:
    db:
        image: postgres:14.3
        restart: always
        ports:
            - "10001:5432"
        environment:
            POSTGRES_DB: comprasresto
            POSTGRES_USER: comprauser
            POSTGRES_PASSWORD: 12345
        container_name: bd-comprasresto
        volumes:
            - ./docker-db/postgres:/var/lib/postgresql/data 

          